runtime: python39

entrypoint: gunicorn -b :$PORT --timeout 600 app:app 


service: default


# Configure your instance size and scaling
instance_class: F1
automatic_scaling:
  max_instances: 10
  min_instances: 1


# DECLARE ENV_VARIABLES
# env_variables:
  # OPENAI_API_KEY: '{insert_key}'
  # GOOGLE_AUTHENTICATION_CREDENTIALS: './key.json'